# Generated by Django 4.2.1 on 2023-06-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_category_alter_portfolio_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
